// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	valueobject "wishlist/domain/valueobject"
)

// MockAuthSessionService is an autogenerated mock type for the AuthSessionService type
type MockAuthSessionService struct {
	mock.Mock
}

type MockAuthSessionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthSessionService) EXPECT() *MockAuthSessionService_Expecter {
	return &MockAuthSessionService_Expecter{mock: &_m.Mock}
}

// ResolveShopperID provides a mock function with given fields: ctx, sessionToken
func (_m *MockAuthSessionService) ResolveShopperID(ctx context.Context, sessionToken string) (valueobject.ShopperId, error) {
	ret := _m.Called(ctx, sessionToken)

	if len(ret) == 0 {
		panic("no return value specified for ResolveShopperID")
	}

	var r0 valueobject.ShopperId
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (valueobject.ShopperId, error)); ok {
		return rf(ctx, sessionToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) valueobject.ShopperId); ok {
		r0 = rf(ctx, sessionToken)
	} else {
		r0 = ret.Get(0).(valueobject.ShopperId)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthSessionService_ResolveShopperID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveShopperID'
type MockAuthSessionService_ResolveShopperID_Call struct {
	*mock.Call
}

// ResolveShopperID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionToken string
func (_e *MockAuthSessionService_Expecter) ResolveShopperID(ctx interface{}, sessionToken interface{}) *MockAuthSessionService_ResolveShopperID_Call {
	return &MockAuthSessionService_ResolveShopperID_Call{Call: _e.mock.On("ResolveShopperID", ctx, sessionToken)}
}

func (_c *MockAuthSessionService_ResolveShopperID_Call) Run(run func(ctx context.Context, sessionToken string)) *MockAuthSessionService_ResolveShopperID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthSessionService_ResolveShopperID_Call) Return(_a0 valueobject.ShopperId, _a1 error) *MockAuthSessionService_ResolveShopperID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthSessionService_ResolveShopperID_Call) RunAndReturn(run func(context.Context, string) (valueobject.ShopperId, error)) *MockAuthSessionService_ResolveShopperID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthSessionService creates a new instance of MockAuthSessionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthSessionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthSessionService {
	mock := &MockAuthSessionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
