// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	aggregate "wishlist/domain/aggregate"

	mock "github.com/stretchr/testify/mock"

	valueobject "wishlist/domain/valueobject"
)

// MockWishlistRepository is an autogenerated mock type for the WishlistRepository type
type MockWishlistRepository struct {
	mock.Mock
}

type MockWishlistRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWishlistRepository) EXPECT() *MockWishlistRepository_Expecter {
	return &MockWishlistRepository_Expecter{mock: &_m.Mock}
}

// AddItem provides a mock function with given fields: ctx, shopperID, simpleSku, configSku
func (_m *MockWishlistRepository) AddItem(ctx context.Context, shopperID valueobject.ShopperId, simpleSku valueobject.SimpleSku, configSku valueobject.ConfigSku) (valueobject.WishlistItemId, error) {
	ret := _m.Called(ctx, shopperID, simpleSku, configSku)

	if len(ret) == 0 {
		panic("no return value specified for AddItem")
	}

	var r0 valueobject.WishlistItemId
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.ShopperId, valueobject.SimpleSku, valueobject.ConfigSku) (valueobject.WishlistItemId, error)); ok {
		return rf(ctx, shopperID, simpleSku, configSku)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.ShopperId, valueobject.SimpleSku, valueobject.ConfigSku) valueobject.WishlistItemId); ok {
		r0 = rf(ctx, shopperID, simpleSku, configSku)
	} else {
		r0 = ret.Get(0).(valueobject.WishlistItemId)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.ShopperId, valueobject.SimpleSku, valueobject.ConfigSku) error); ok {
		r1 = rf(ctx, shopperID, simpleSku, configSku)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWishlistRepository_AddItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddItem'
type MockWishlistRepository_AddItem_Call struct {
	*mock.Call
}

// AddItem is a helper method to define mock.On call
//   - ctx context.Context
//   - shopperID valueobject.ShopperId
//   - simpleSku valueobject.SimpleSku
//   - configSku valueobject.ConfigSku
func (_e *MockWishlistRepository_Expecter) AddItem(ctx interface{}, shopperID interface{}, simpleSku interface{}, configSku interface{}) *MockWishlistRepository_AddItem_Call {
	return &MockWishlistRepository_AddItem_Call{Call: _e.mock.On("AddItem", ctx, shopperID, simpleSku, configSku)}
}

func (_c *MockWishlistRepository_AddItem_Call) Run(run func(ctx context.Context, shopperID valueobject.ShopperId, simpleSku valueobject.SimpleSku, configSku valueobject.ConfigSku)) *MockWishlistRepository_AddItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.ShopperId), args[2].(valueobject.SimpleSku), args[3].(valueobject.ConfigSku))
	})
	return _c
}

func (_c *MockWishlistRepository_AddItem_Call) Return(_a0 valueobject.WishlistItemId, _a1 error) *MockWishlistRepository_AddItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWishlistRepository_AddItem_Call) RunAndReturn(run func(context.Context, valueobject.ShopperId, valueobject.SimpleSku, valueobject.ConfigSku) (valueobject.WishlistItemId, error)) *MockWishlistRepository_AddItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetByShopperId provides a mock function with given fields: ctx, shopperID, pagination
func (_m *MockWishlistRepository) GetByShopperId(ctx context.Context, shopperID valueobject.ShopperId, pagination valueobject.Pagination) (*aggregate.Wishlist, error) {
	ret := _m.Called(ctx, shopperID, pagination)

	if len(ret) == 0 {
		panic("no return value specified for GetByShopperId")
	}

	var r0 *aggregate.Wishlist
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.ShopperId, valueobject.Pagination) (*aggregate.Wishlist, error)); ok {
		return rf(ctx, shopperID, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.ShopperId, valueobject.Pagination) *aggregate.Wishlist); ok {
		r0 = rf(ctx, shopperID, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aggregate.Wishlist)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.ShopperId, valueobject.Pagination) error); ok {
		r1 = rf(ctx, shopperID, pagination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWishlistRepository_GetByShopperId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByShopperId'
type MockWishlistRepository_GetByShopperId_Call struct {
	*mock.Call
}

// GetByShopperId is a helper method to define mock.On call
//   - ctx context.Context
//   - shopperID valueobject.ShopperId
//   - pagination valueobject.Pagination
func (_e *MockWishlistRepository_Expecter) GetByShopperId(ctx interface{}, shopperID interface{}, pagination interface{}) *MockWishlistRepository_GetByShopperId_Call {
	return &MockWishlistRepository_GetByShopperId_Call{Call: _e.mock.On("GetByShopperId", ctx, shopperID, pagination)}
}

func (_c *MockWishlistRepository_GetByShopperId_Call) Run(run func(ctx context.Context, shopperID valueobject.ShopperId, pagination valueobject.Pagination)) *MockWishlistRepository_GetByShopperId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.ShopperId), args[2].(valueobject.Pagination))
	})
	return _c
}

func (_c *MockWishlistRepository_GetByShopperId_Call) Return(_a0 *aggregate.Wishlist, _a1 error) *MockWishlistRepository_GetByShopperId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWishlistRepository_GetByShopperId_Call) RunAndReturn(run func(context.Context, valueobject.ShopperId, valueobject.Pagination) (*aggregate.Wishlist, error)) *MockWishlistRepository_GetByShopperId_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveItemByConfigSku provides a mock function with given fields: ctx, shopperID, configSku
func (_m *MockWishlistRepository) RemoveItemByConfigSku(ctx context.Context, shopperID valueobject.ShopperId, configSku valueobject.ConfigSku) error {
	ret := _m.Called(ctx, shopperID, configSku)

	if len(ret) == 0 {
		panic("no return value specified for RemoveItemByConfigSku")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.ShopperId, valueobject.ConfigSku) error); ok {
		r0 = rf(ctx, shopperID, configSku)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWishlistRepository_RemoveItemByConfigSku_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveItemByConfigSku'
type MockWishlistRepository_RemoveItemByConfigSku_Call struct {
	*mock.Call
}

// RemoveItemByConfigSku is a helper method to define mock.On call
//   - ctx context.Context
//   - shopperID valueobject.ShopperId
//   - configSku valueobject.ConfigSku
func (_e *MockWishlistRepository_Expecter) RemoveItemByConfigSku(ctx interface{}, shopperID interface{}, configSku interface{}) *MockWishlistRepository_RemoveItemByConfigSku_Call {
	return &MockWishlistRepository_RemoveItemByConfigSku_Call{Call: _e.mock.On("RemoveItemByConfigSku", ctx, shopperID, configSku)}
}

func (_c *MockWishlistRepository_RemoveItemByConfigSku_Call) Run(run func(ctx context.Context, shopperID valueobject.ShopperId, configSku valueobject.ConfigSku)) *MockWishlistRepository_RemoveItemByConfigSku_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.ShopperId), args[2].(valueobject.ConfigSku))
	})
	return _c
}

func (_c *MockWishlistRepository_RemoveItemByConfigSku_Call) Return(_a0 error) *MockWishlistRepository_RemoveItemByConfigSku_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWishlistRepository_RemoveItemByConfigSku_Call) RunAndReturn(run func(context.Context, valueobject.ShopperId, valueobject.ConfigSku) error) *MockWishlistRepository_RemoveItemByConfigSku_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWishlistRepository creates a new instance of MockWishlistRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWishlistRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWishlistRepository {
	mock := &MockWishlistRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
