// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	port "product_discovery/domain/port"

	mock "github.com/stretchr/testify/mock"
)

// MockPlatformProductClient is an autogenerated mock type for the PlatformProductClient type
type MockPlatformProductClient struct {
	mock.Mock
}

type MockPlatformProductClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlatformProductClient) EXPECT() *MockPlatformProductClient_Expecter {
	return &MockPlatformProductClient_Expecter{mock: &_m.Mock}
}

// FetchProductDetail provides a mock function with given fields: ctx, configSku
func (_m *MockPlatformProductClient) FetchProductDetail(ctx context.Context, configSku string) (*port.RawProductDetailPayload, error) {
	ret := _m.Called(ctx, configSku)

	if len(ret) == 0 {
		panic("no return value specified for FetchProductDetail")
	}

	var r0 *port.RawProductDetailPayload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*port.RawProductDetailPayload, error)); ok {
		return rf(ctx, configSku)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *port.RawProductDetailPayload); ok {
		r0 = rf(ctx, configSku)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*port.RawProductDetailPayload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, configSku)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlatformProductClient_FetchProductDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchProductDetail'
type MockPlatformProductClient_FetchProductDetail_Call struct {
	*mock.Call
}

// FetchProductDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - configSku string
func (_e *MockPlatformProductClient_Expecter) FetchProductDetail(ctx interface{}, configSku interface{}) *MockPlatformProductClient_FetchProductDetail_Call {
	return &MockPlatformProductClient_FetchProductDetail_Call{Call: _e.mock.On("FetchProductDetail", ctx, configSku)}
}

func (_c *MockPlatformProductClient_FetchProductDetail_Call) Run(run func(ctx context.Context, configSku string)) *MockPlatformProductClient_FetchProductDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPlatformProductClient_FetchProductDetail_Call) Return(_a0 *port.RawProductDetailPayload, _a1 error) *MockPlatformProductClient_FetchProductDetail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlatformProductClient_FetchProductDetail_Call) RunAndReturn(run func(context.Context, string) (*port.RawProductDetailPayload, error)) *MockPlatformProductClient_FetchProductDetail_Call {
	_c.Call.Return(run)
	return _c
}

// FetchProductFilters provides a mock function with given fields: ctx, params
func (_m *MockPlatformProductClient) FetchProductFilters(ctx context.Context, params port.ProductListParams) (*port.RawFilterPayload, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for FetchProductFilters")
	}

	var r0 *port.RawFilterPayload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.ProductListParams) (*port.RawFilterPayload, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.ProductListParams) *port.RawFilterPayload); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*port.RawFilterPayload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.ProductListParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlatformProductClient_FetchProductFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchProductFilters'
type MockPlatformProductClient_FetchProductFilters_Call struct {
	*mock.Call
}

// FetchProductFilters is a helper method to define mock.On call
//   - ctx context.Context
//   - params port.ProductListParams
func (_e *MockPlatformProductClient_Expecter) FetchProductFilters(ctx interface{}, params interface{}) *MockPlatformProductClient_FetchProductFilters_Call {
	return &MockPlatformProductClient_FetchProductFilters_Call{Call: _e.mock.On("FetchProductFilters", ctx, params)}
}

func (_c *MockPlatformProductClient_FetchProductFilters_Call) Run(run func(ctx context.Context, params port.ProductListParams)) *MockPlatformProductClient_FetchProductFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.ProductListParams))
	})
	return _c
}

func (_c *MockPlatformProductClient_FetchProductFilters_Call) Return(_a0 *port.RawFilterPayload, _a1 error) *MockPlatformProductClient_FetchProductFilters_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlatformProductClient_FetchProductFilters_Call) RunAndReturn(run func(context.Context, port.ProductListParams) (*port.RawFilterPayload, error)) *MockPlatformProductClient_FetchProductFilters_Call {
	_c.Call.Return(run)
	return _c
}

// FetchProductList provides a mock function with given fields: ctx, params
func (_m *MockPlatformProductClient) FetchProductList(ctx context.Context, params port.ProductListParams) (*port.RawProductListPayload, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for FetchProductList")
	}

	var r0 *port.RawProductListPayload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.ProductListParams) (*port.RawProductListPayload, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.ProductListParams) *port.RawProductListPayload); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*port.RawProductListPayload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.ProductListParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlatformProductClient_FetchProductList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchProductList'
type MockPlatformProductClient_FetchProductList_Call struct {
	*mock.Call
}

// FetchProductList is a helper method to define mock.On call
//   - ctx context.Context
//   - params port.ProductListParams
func (_e *MockPlatformProductClient_Expecter) FetchProductList(ctx interface{}, params interface{}) *MockPlatformProductClient_FetchProductList_Call {
	return &MockPlatformProductClient_FetchProductList_Call{Call: _e.mock.On("FetchProductList", ctx, params)}
}

func (_c *MockPlatformProductClient_FetchProductList_Call) Run(run func(ctx context.Context, params port.ProductListParams)) *MockPlatformProductClient_FetchProductList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.ProductListParams))
	})
	return _c
}

func (_c *MockPlatformProductClient_FetchProductList_Call) Return(_a0 *port.RawProductListPayload, _a1 error) *MockPlatformProductClient_FetchProductList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlatformProductClient_FetchProductList_Call) RunAndReturn(run func(context.Context, port.ProductListParams) (*port.RawProductListPayload, error)) *MockPlatformProductClient_FetchProductList_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPlatformProductClient creates a new instance of MockPlatformProductClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlatformProductClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlatformProductClient {
	mock := &MockPlatformProductClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
